Add patches for nginx 1.25.0 and corresponding nginx-tests patch
wolfSSL/wolfssl-nginx pull request #22
Opened 2023-06-15 14:12 UTC by julek-wolfssl

Passes ssl tests when nginx is configured with
  ./auto/configure --with-wolfssl=/usr/local --with-http_ssl_module --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --with-mail --with-mail_ssl_module
And the tests that are confirmed to pass (with the patch applied):
  TEST_NGINX_BINARY=../nginx/objs/nginx prove *ssl*

2023-06-15 14:17 UTC, julek-wolfssl commented
Depends on https://github.com/wolfSSL/wolfssl/pull/6515

2023-06-21 23:57 UTC, kareem-wolfssl requested changes

2023-06-23 11:15 UTC, julek-wolfssl commented on nginx-1.25.0-wolfssl.patch
> ++            #endif
Confirmed not needed and removed.

2023-06-23 11:15 UTC, julek-wolfssl commented on nginx-1.25.0-wolfssl.patch
> ++#if (defined SSL_CTX_set1_curves_list || defined SSL_CTRL_SET_CURVES_LIST) || \
Confirmed not needed and removed.

2023-06-23 17:35 UTC, kareem-wolfssl requested changes
Code looks good.
Is it possible to fix the PR test?  It looks like it's missing a dependency to build nginx:
```
./auto/configure: error: the HTTP rewrite module requires the PCRE library.
You can either disable the module by using --without-http_rewrite_module
option, or install the PCRE library into the system, or build the PCRE library
statically from the source with nginx by using --with-pcre=<path> option.
```

2023-06-27 08:04 UTC, julek-wolfssl commented
@kareem-wolfssl  Since I added testing on the wolfSSL side, can we ignore this test failure? I'll figure out how the tests here work and how they can be fixed.

2023-06-27 17:42 UTC, kareem-wolfssl approved these changes
Good point.
We may consider just getting rid of this Jenkins test now that we have Github actions continuously testing nginx.

2023-06-27 17:42 UTC, merged